import streamlit as st
from utilidades import *

def run():
    #Configuracion de la página (como se ve la pestaña del navegador, layout de la pagina, etc)
    st.set_page_config(
    page_title="Chromidex-UdeC",
    page_icon="imagenes/logoAPP.jpeg",
    layout="wide"
    )

    #Elementos de ls sidebar (ícono uded)
    leng = lenguaje_selectbox()
    write_espacios_sbar(30)
    st.sidebar.image("imagenes/marca_udec2.png")


    #AQUI COMIENZA EL CONTENIDO DE LA PAGINA (CUERPO)

    #Imagenes al inicio
    col1, _, col2 = st.columns([1, 3, 2])
    col1.image('imagenes/logoAPP.jpeg')
    col2.image('imagenes/udec.gif', use_column_width='always')

    # CONTENIDO EN INGLES
    if leng == lenguajes[0]:
        st.header('Chromindex-UdeC')

        """
        **Chromindex-UdeC**, a simple method for calculating karyotypic asymmetry
        indices from excel tables generated by the MicroMeasure program.

        Álvaro Guzmán Chacón¹, Carlos Baeza Perry² & Pedro Pinacho Davidson³.

         ¹Facultad de Ciencias Físicas y Matemáticas, Departamento de Ingeniería Civil Matemática,
          Universidad de Concepción, Concepción, Chile.

         ²Facultad de Ciencias Naturales y Oceanográficas, Departamento de Botánica,
         Universidad de Concepción, Concepción, Chile.

         ³Facultad de Ingeniería, Departamento de Ingeniería Informática y Ciencias de la
         Computación, Universidad de Concepción, Concepción, Chile.
         """


    # CONTENIDO EN ESPAÑOL
    else:
        st.header('Chromindex-UdeC')

        """
        **Chromindex-UdeC**, un método simple para calcular índices de asimetría
        cariotípica a partir de tablas Excel generadas por el programa MicroMeasure.

        Álvaro Guzmán Chacón¹, Carlos Baeza Perry² & Pedro Pinacho Davidson³.

         ¹Facultad de Ciencias Físicas y Matemáticas, Departamento de Ingeniería Civil Matemática,
          Universidad de Concepción, Concepción, Chile.

         ²Facultad de Ciencias Naturales y Oceanográficas, Departamento de Botánica,
         Universidad de Concepción, Concepción, Chile.

         ³Facultad de Ingeniería, Departamento de Ingeniería Informática y Ciencias de la
         Computación, Universidad de Concepción, Concepción, Chile.
         """

    #Imagenes al final de la página
    write_espacios(16)
    st.image('imagenes/banner.png')
    #footer()





if __name__ == "__main__":
    run()
